name: Post-commit Checks

on:
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Run pylint
      run: |
        pylint pasito_event_scripts/ tests/
    - name: Run tests
      run: |
        pytest --maxfail=3 --disable-warnings -v
    - name: Check for sensitive data
      run: |
        if grep -r "password\|secret\|key\|token" . --include="*.py" --include="*.md" --include="*.txt"; then
          echo "Potential sensitive data found in files"
          exit 1
        fi 